### ISSUE TITLE
object 'gene.idtype.bods' not found

### ISSUE THREAD

**Issue by vnimmunol** [egeulgen/pathfindR#10]
When I run pathfindR on example data RA_input, it runs perfectly fine. But when I run it on my dataset (attached) I get the following error:

Error in gene.idtype %in% gene.idtype.bods[[species]] :
  object 'gene.idtype.bods' not found

I get the same error on two different platforms, R 3.5.1 on Widows and R 3.4.3 on Ubuntu, so it seems to be a software issue. Can you please help to check.

Thanks,
VN

[dgeDataFrame.zip](https://github.com/egeulgen/pathfindR/files/2564964/dgeDataFrame.zip)

**Comment by egeulgen** [comment]
This is a frequently encountered issue that arises when the workspace is cleared after loading `pathfindR` (see [wiki - frequently encountered issues](https://github.com/egeulgen/pathfindR/wiki/Frequently-encountered-issues#geneidtypebods-not-found)) . This is an issue with the package `pathview` that `pathfindR` depends on for KEGG pathway visualization. Upon loading, `pathview` loads several objects including `gene.idtype.bods`.

Two possible solutions:

1- Close R/RStudio and re-open

2- Unload and reload pathfindR and pathview, i.e.:

``` r
detach("package:pathfindR", unload=TRUE)
detach("package:pathview", unload=TRUE)
library(pathfindR) 
```
