### ISSUE TITLE
cluster_pathways runs indefinitely 

### ISSUE THREAD

**Issue by oliverschilling** [egeulgen/pathfindR#11]
Hello,
when running pathfindR with the attached list, the  "run_pathfindR" works nicely, but "cluster_pathways" seems to b stuck (I killed the process after 4 hrs). 

Here is how I run it ("my" RA_input.txt is attached):
source("http://bioconductor.org/biocLite.R")
biocLite(suppressUpdates=TRUE)
library(pathfindR)
RA_input <- read.table("RA_input.txt",header=TRUE)

RA_output <- run_pathfindR(RA_input, gene_sets="Reactome", search_method="GR", iterations=5, n_processes = 6, adj_method="bonferroni",grOverlap=0.5,sig_gene_thr=10,enrichment_threshold = 0.05,output_dir="reactome")

RA_clustered <- cluster_pathways(RA_output, kappa_threshold = 0.35)

Thanks for any advice. BTW: it works nicely with other expression datasets, so installation etc is good.
[RA_input.txt](https://github.com/egeulgen/pathfindR/files/2661021/RA_input.txt)

**Comment by egeulgen** [comment]
Hello,
When I run it the result is 466 reactome pathways. The clustering functions (specifically the function that creates the kappa statistic matrix) has to iterate over the matrix of pathways x genes (of which there were 11932 in the result). I'll try and see if the kappa matrix creation can be faster but I doubt it. Meanwhile, I suggest filtering the output pathways by their highest p values (increasing the threshold from 0.05 to 0.001, for example). Another option would be to filter the input genes more strictly (i.e. decrease the `p_val_threshold` argument from 0.05 to a lower value or the incorporate LFC filtering, e.g. |LFC| >= 1)

**Comment by egeulgen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [faster kappa matrix calculation](https://trello.com/c/j320RPHz/66-faster-kappa-matrix-calculation)

**Comment by egeulgen** [comment]
hey @oliverschilling,
I've made some improvements in the function that calculates the kappa matrix, it now seems to be significantly faster (vs. an indefinite run :) ):

```r
Unit: seconds
                                expr    min    lq   mean median     uq    max neval
 create_kappa_matrix_NEW(issue11_df) 16.895 17.26 17.384 17.377 17.648 17.845    10
```

I will see if it can become any faster with further optimization. For now, hope this works OK.

Until the next CRAN release, you can use this updated function by installing the development version:
```r
install.packages("devtools") # if you have not installed "devtools" package
devtools::install_github("egeulgen/pathfindR")
```

**Comment by egeulgen** [comment]
Hello again,
I've made some further improvements to the kappa matrix calculation (see bf26405b9386f53ccdbf32be3be941a733c5810a). Latest seems much better:

```r
Unit: seconds
                            expr    min    lq   mean median     uq    max neval
 create_kappa_matrix(issue11_df) 2.9692 3.036 3.1732 3.1344 3.1906 3.6094    10
```

This is again available in the latest development version and will be in the next CRAN release.
Best,
-E
