### ISSUE TITLE
Legend title in the term_gene_heatmap

### ISSUE THREAD

**Issue by zillurbmb51** [egeulgen/pathfindR#112]
Hi,

How can I change/create custom legend title in the term_gene_heatmap?

I have the attached df as input. I need to label the color indicates in the right side of the attached figure. 

How could I do this? So far, I have tried with `+labs (color='title')` , `+ guides(color=guide_legend("MaxCADD"))` and `+ legend_title('MaxCADD')` but got no result. Any help?
![conjFDR_0 05_SCZ_vs_BASOPHIL_PATH](https://user-images.githubusercontent.com/12833907/149286113-e0c290a0-eab9-4798-8bb1-9961adca3bd6.png)
[example_input_df.csv](https://github.com/egeulgen/pathfindR/files/7860848/example_input_df.csv)

`R version 4.1.2 (2021-11-01)` and `Package pathfindR version 1.6.3.9002`

**Comment by egeulgen** [comment]
the above fix (pathfindR 1.6.3.9003) resolves this issue. I introduced a new argument to `term_gene_heatmap()` called `legend_title`. Which is "change" by default but you can change it to "MaxCADD" or whatever you wish

**Comment by zillurbmb51** [comment]
Thanks.
