### ISSUE TITLE
run_pathfindR error: helvetica

### ISSUE THREAD

**Issue by adamxmiranda** [egeulgen/pathfindR#117]
Hi. I'm trying to run the run_pathfindR() but keep running into an error when it tries to generate the plots:

`Saving colored pathway diagrams of 10 KEGG pathways

  |                                                                      |   0%
Error in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)): R: unable to read font `helvetica' @ error/annotate.c/RenderFreetype/1474
Traceback:`

From some searching around I think this has something to do with the magick imaging, but I have no idea how to remedy this specific issue. Any help you can provide will be much appreciated.

**Comment by egeulgen** [comment]
Hey,

Installing the Helvetica font should resolve the issue. If it persists, please open an issue on [the magick repo](https://github.com/ropensci/magick/issues)

You may also disable these plots by setting `visualize_enriched_terms =FALSE` when running `run_pathfindR()`

Best,
-E
