### ISSUE TITLE
Unchanged genes marked as light green in pathway visualization

### ISSUE THREAD

**Issue by B-McBean** [egeulgen/pathfindR#119]
Hello! This is a really great tool and the documentation is excellent! I am having a small problem when I'm using the wrapper function run_pathfindR (and the visualize_hsa_KEGG function by itself). Genes that do not have changed expression in the pathway are marked as light green, which makes it looks like they have changed expression. 

I'm wondering if this is a problem others have experienced and if there's any way to make unchanged genes (or rather, genes not even included on the significantly changed genes list) white instead?

Thanks!

(I've attached pictures to show what I mean in case it isn't clear. In the one with blue and orange, I used the visualize_hsa_KEGG function and changed the low and high to blue and orange (node_cols = c("blue", "gray", "orange")) but there's still green on here for genes in the pathway whose expression does not change. The same is occurring when I use run_pathfindR, which is the other image with the default red and green for high and low.)

![hsa04066_pathfindR](https://user-images.githubusercontent.com/35742060/165558104-348eaca4-492b-4da8-b0df-d617e82ab937.png)

![hsa04066_pathfindR](https://user-images.githubusercontent.com/35742060/165558167-586e71c4-096f-4f23-a00b-d194c89b3be5.png)

**Comment by egeulgen** [comment]
Hello, 
This happens with large (>60 genes) KEGG pathways. For these we have to disregard the white color for non-input genes, otherwise KEGG API complains.
I'll try to think of a workaround and update you here if I can find one.
Best,
-E
