### ISSUE TITLE
Error when supplying input with 200 genes

### ISSUE THREAD

**Issue by dalhoomist** [egeulgen/pathfindR#12]
I just started using pathfindR. When I supply a dataframe as input with 100 or less genes, I get a message indicating there are no enriched pathways:
`Astro_output <- run_pathfindR(as.data.frame(dge1[1:100,]), enrichment_threshold = 0.2, adj_method = "BH", visualize_pathways=TRUE)`

> Testing input
> 
> The input looks OK
> 
> Processing input. Converting gene symbols, if necessary (and if human gene symbols provied)
> 
> Could not find any interactions for 28 (28%) genes in the PIN
> 
> Performing Active Subnetwork Search and Enrichment
> 
> Warning messages:
> 1: In pathfindR::input_processing(input, p_val_threshold, pin_path,  :
>   pathfindR cannot handle p values < 1e-13
> These were changed to 1e-13
> 2: In run_pathfindR(as.data.frame(dge1[1:100, ]), enrichment_threshold = 0.2,  :
>   Did not find any enriched pathways!`
> 
> 

When I use the entire list or anything above 200 genes I get this error:

`Astro_output <- run_pathfindR(as.data.frame(dge1[1:200,]), enrichment_threshold = 0.2, adj_method = "BH", visualize_pathways=TRUE)`
> Testing input
> 
> The input looks OK
> 
> Processing input. Converting gene symbols, if necessary (and if human gene symbols provied)
> 
> Could not find any interactions for 47 (23.62%) genes in the PIN
> 
> Performing Active Subnetwork Search and Enrichment
> 
> Processing the enrichment results over all iterations 
> 
> Annotating involved genes and visualizing pathways
> 
> 
> Error in UseMethod("select_") : 
>   no applicable method for 'select_' applied to an object of class "c('OrgDb', 'AnnotationDb', 'envRefClass', '.environment', 'refClass', 'environment', 'refObject', 'AssayData')"
> In addition: Warning message:
> In pathfindR::input_processing(input, p_val_threshold, pin_path,  :
>   pathfindR cannot handle p values < 1e-13
> These were changed to 1e-13
> Error in mol.sum(gene.data, gene.idmap) : no ID can be mapped!`
> 

I tried supplying 200, 300, and 600 genes and I get the same error. Is there a solution?

I attached the dataframe of genes.
[gde.txt](https://github.com/egeulgen/pathfindR/files/2777471/gde.txt)

Here is my session.info:
`

> sessionInfo()
> R version 3.5.1 (2018-07-02)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows >= 8 x64 (build 9200)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
> [4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    
> 
> attached base packages:
> [1] parallel  stats4    stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>  [1] pathfindR_1.3.0             pathview_1.22.1             scran_1.10.2                pheatmap_1.0.12            
>  [5] foreach_1.4.4               Rtsne_0.15                  scater_1.10.1               SingleCellExperiment_1.4.1 
>  [9] SummarizedExperiment_1.12.0 DelayedArray_0.8.0          BiocParallel_1.16.2         matrixStats_0.54.0         
> [13] GenomicRanges_1.34.0        GenomeInfoDb_1.18.1         ggplot2_3.1.0               tibble_2.0.1               
> [17] dplyr_0.7.8                 RColorBrewer_1.1-2          org.Hs.eg.db_3.7.0          AnnotationDbi_1.44.0       
> [21] IRanges_2.16.0              S4Vectors_0.20.1            Biobase_2.42.0              BiocGenerics_0.28.0        
> [25] knitr_1.21                  readr_1.3.1                
> 
> loaded via a namespace (and not attached):
>  [1] bitops_1.0-6             bit64_0.9-7              doParallel_1.0.14        httr_1.4.0              
>  [5] dynamicTreeCut_1.63-1    Rgraphviz_2.26.0         tools_3.5.1              utf8_1.1.4              
>  [9] R6_2.3.0                 HDF5Array_1.10.1         vipor_0.4.5              DBI_1.0.0               
> [13] lazyeval_0.2.1           colorspace_1.3-2         withr_2.1.2              tidyselect_0.2.5        
> [17] gridExtra_2.3            bit_1.1-14               compiler_3.5.1           cli_1.0.1               
> [21] graph_1.60.0             BiocNeighbors_1.0.0      KEGGgraph_1.42.0         scales_1.0.0            
> [25] stringr_1.3.1            digest_0.6.18            rmarkdown_1.11           XVector_0.22.0          
> [29] pkgconfig_2.0.2          htmltools_0.3.6          limma_3.38.3             rlang_0.3.1             
> [33] rstudioapi_0.9.0         RSQLite_2.1.1            BiocInstaller_1.32.1     DelayedMatrixStats_1.4.0
> [37] bindr_0.1.1              RCurl_1.95-4.11          magrittr_1.5             GenomeInfoDbData_1.2.0  
> [41] Matrix_1.2-15            fansi_0.4.0              Rcpp_1.0.0               ggbeeswarm_0.6.0        
> [45] munsell_0.5.0            Rhdf5lib_1.4.2           viridis_0.5.1            edgeR_3.24.3            
> [49] stringi_1.2.4            zlibbioc_1.28.0          rhdf5_2.26.2             plyr_1.8.4              
> [53] grid_3.5.1               blob_1.1.1               crayon_1.3.4             lattice_0.20-38         
> [57] Biostrings_2.50.2        hms_0.4.2                KEGGREST_1.22.0          locfit_1.5-9.1          
> [61] pillar_1.3.1             igraph_1.2.2             reshape2_1.4.3           codetools_0.2-16        
> [65] XML_3.98-1.16            glue_1.3.0               evaluate_0.12            BiocManager_1.30.4      
> [69] png_0.1-7                gtable_0.2.0             purrr_0.2.5              assertthat_0.2.0        
> [73] xfun_0.4                 viridisLite_0.3.0        iterators_1.0.10         beeswarm_0.2.3          
> [77] memoise_1.1.0            bindrcpp_0.2.2           statmod_1.4.30  `
>

**Comment by egeulgen** [comment]
@dalhoomist this seems to be an issue with the package `pathview`, I tried reproducing it but did not get any error. Do you mind writing to the maintainer (Weijun Luo <luo_weijun at yahoo.com>) stating that you have the following error: 
`Error in UseMethod("select_") :
no applicable method for 'select_' applied to an object of class "c('OrgDb', 'AnnotationDb', 'envRefClass', '.environment', 'refClass', 'environment', 'refObject', 'AssayData')"`.

Meanwhile, I believe setting `visualize_pathways=FALSE` should fix the issue (though, you will be missing the pathway diagrams)
Best,
-E

**Comment by dalhoomist** [comment]
Thanks Egeulgen. I will write to the maintainer and give it another try.

**Comment by dalhoomist** [comment]
Hi,

I detached the dplyr package and gave it a shot. Works fine this way.

Thanks
Osama

**Comment by Kur1sutaru** [comment]
## Processing input. Converting gene symbols,
          if necessary (and if human gene symbols provided)
Number of genes provided in input: 12450
Number of genes in input after p-value filtering: 376
pathfindR cannot handle p values < 1e-13. These were changed to 1e-13
Could not find any interactions for 81 (21.54%) genes in the PIN
Final number of genes in input: 295
## Performing Active Subnetwork Search and Enrichment
## Processing the enrichment results over all iterations
## Annotating involved genes and visualizing enriched terms
Error in `$<-.data.frame`(`*tmp*`, "KEGG_ID", value = "hsa:") : 
  replacement has 1 row, data has 0
