### ISSUE TITLE
Issues with KEGGgraph and retrieving KEGG pngs

### ISSUE THREAD

**Issue by apelin20** [egeulgen/pathfindR#121]
Hello,

pathfindR is failing to download KEGG pngs (sorry have to use pastebin):

https://pastebin.com/t7iv3K9j

I believe the issue is with KEGGgraph:

https://pastebin.com/d7n6syyP

Where in pathfindR can I replace the code of using KEGGgraph to download KEGG pngs with something else?

KEGGgraph_1.50.0
R ver 4.0.2
pathfindR Version: 1.6.3

Thanks,
Adrian

**Comment by egeulgen** [comment]
Hey,

If this persists, please raise an issue with KEGGgraph.

Meanwhile, if visualization is not necessary, you may set `visualize_enriched_terms=FALSE` in `run_pathfindR()` and you could also visualize the enriched terms later via `visualize_terms()`

Hope this helps,
-E

**Comment by apelin20** [comment]
Thanks, that was an easy fix. Going back to KEGG pathways and KEGGgraph error. Is there any way I can download all the KEGG pathways from here for example (https://www.kegg.jp/kegg/download/Readme/README.pathway) and point pathfindR to them locally?

**Comment by egeulgen** [comment]
I'm afraid that's not possible.
However, updating to the latest version of KEGGREST resolves the issue. To be clear, you don't need KEGGgraph

**Comment by apelin20** [comment]
Thanks Ege, I got the same answer from KEGGREST - https://github.com/Bioconductor/KEGGREST/issues/12

installing through install_github("Bioconductor/KEGGREST") did the trick.
