### ISSUE TITLE
Error: Failed to extract KEGG image path from response. 

### ISSUE THREAD

**Issue by aish181095** [egeulgen/pathfindR#122]
Hi,

I am trying to run the pathfindR for my dataset. When previously run (around a week ago), it was able to extract the KEGG pathways. But it has been showing this error for the same code when running the script today. Would appreciate your help. Thanks.

Here's the original error message:
'color.pathway.by.objects()' failed to extract KEGG image path from response.
Cannot download PNG file: NA
Here's the original error message:
invalid 'url' argument

**Comment by egeulgen** [comment]
Hello,

I believe there was an issue with KEGGREST (the dependency of pathfindR for obtaining KEGG diagrams), which seems to be recently fixed. Updating should resolve the issue:

```r
BiocManager::install("KEGGREST")
```

**Comment by aish181095** [comment]
Thanks for the reply.

But even after updating, it shows the same error.
