### ISSUE TITLE
Issue with KEGG server connection when running pathfindr 

### ISSUE THREAD

**Issue by junli1988** [egeulgen/pathfindR#124]
**Describe the bug**
I keep getting an error message when downloading the KEGG pathway in the first step 

**To Reproduce**
1. Prepare input as '...'
2. Run the following function: mmu_kegg_descriptions <- keggList("pathway", "mmu")
3. See error: 
Error in curl::curl_fetch_memory(url, handle = handle) : 
 Failure when receiving data from the peer

**Expected behavior**
Download the KEGG list for pathway info on mus musculus 

**Desktop (please complete the following information):**
 - OS: Windows
 - Version [e.g. 10.14.5]

**Comment by egeulgen** [comment]
What version of KEGGREST are you using?  1.36.2 works for me
