### ISSUE TITLE
error in using pathfindR package. 

### ISSUE THREAD

**Issue by Mahla-As** [egeulgen/pathfindR#138]
I am using the pathfindR package. I get an error when I run this command:

output_df <- run_pathfindR(DEG,gene_sets = 'KEGG', iterations = 5, n_processes = 2)

This is the error:

## Testing input
The input looks OK
## Processing input. Converting gene symbols,
          if necessary (and if human gene symbols provided)
Number of genes provided in input: 14
Number of genes in input after p-value filtering: 13
Found interactions for all genes in the PIN
Final number of genes in input: 13
## Annotating involved genes and visualizing enriched terms

Downloading pathway diagrams of 1 KEGG pathways

  |                                                                                                                            |   0%Cannot retrieve PNG url: hsa05418
Here's the original error message:
'color.pathway.by.objects()' failed to extract KEGG image path from response.
Cannot download PNG file: NA
Here's the original error message:
invalid 'url' argument
  |============================================================================================================================| 100%
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/geode2/soft/hps/rhel7/r/4.0.4/lib64/R/library/magick/libs/magick.so':
  libMagick++-7.Q16HDRI.so.5: cannot open shared object file: No such file or directory

This is the sessionInfo:

R version 4.0.4 (2021-02-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux

Matrix products: default
BLAS/LAPACK: /geode2/soft/hps/rhel7/intel/19.5/compilers_and_libraries_2019.5.281/linux/mkl/lib/intel64_lin/libmkl_rt.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] pathfindR_1.6.3         pathfindR.data_1.1.2    KEGGREST_1.30.1        
[4] KEGGgraph_1.50.0        packagestats_0.0.5.0000

**Comment by egeulgen** [comment]
Can you please fill out the template as requested?

**Comment by egeulgen** [comment]
this is an error due to an issue with magick. see [here](https://github.com/ropensci/magick/issues/229) for a possible solution
