### ISSUE TITLE
Visualization 

### ISSUE THREAD

**Issue by Elseedy28** [egeulgen/pathfindR#147]
Hello , 
 i have a problem concerning the visualization method . i cannot have the bubble plot for the 10 enriched pathway and also when i have the PPi network it is not well labelled as term gene graph in your pipeline  attached an example 
![canonical_Wnt_signaling_pathway](https://user-images.githubusercontent.com/115556489/196208328-dc7f9925-f81a-46e1-bd84-0c2202197083.png)

and this is the code i am using there is no bug or error but i don't get any graph
enrichment_chart(final_res[1:10, ])
term_gene_graph(final_res[1:10, ])
score_terms(final_res[1:10,])

Thanks
heba

**Comment by egeulgen** [comment]
hello heba,

that is not the output of `term_gene_graph()`, it's the output `visualize_term_interactions()` and you can remove the legend  by setting `show_legend=FALSE` either in `visualize_term_interactions()` or (better) `visualize_terms()`.


> enrichment_chart(final_res[1:10, ])
> term_gene_graph(final_res[1:10, ])

The output of these are ggplot2 objects and are automatically displayed in the Plots console (if you are not using an IDE, assign the output to a variable, e.g., `g <- enrichment_chart(final_res[1:10, ])` and you can save the plot by `ggplot2::ggsave()`

For `score_terms()`, you need the experiment (expression/methylation) matrix as another input.

Hope this helps,
-E
