### ISSUE TITLE
pathfindR using proteomics data

### ISSUE THREAD

**Issue by lyons89** [egeulgen/pathfindR#148]
Hello Ege,

I'm a fan of pathfindR and use it all the time for my proteomics pathway analysis needs. I had a quick question about the enrichment analysis that pathfindR performs. Based on my limited experience it looks like you use ORA for the pathway analysis step. I was wondering since in proteomics we never identify all the proteins in a sample if the background should be changed to only include proteins that were identified in the analysis. I don't know if you have any experience with proteomics pathway enrichment but I'd like to hear your opinion on it.

Best,
Scott

**Comment by egeulgen** [comment]
Hello Scott,

By default, the background for ORA is the set of all proteins in the PIN. So my suggestion would be to use a subset of the PIN to only contain proteins identified in your analysis (hence using a custom PIN, you can read more about that in the vignettes).

Hope this helps,
Best,
-E

**Comment by ozanozisik** [comment]
Hello,
Currently changing the PIN is the only way to change the background genes in pathfindR  however it is not a good way as the interactions are there even if you do not measure.
We will add an argument soon to change the background gene set in ORA.
Thank you for highlighting this.
Best,
Ozan

**Comment by Apirog9** [comment]
Is this currently possible to define a background?
