### ISSUE TITLE
ensembl ID instead of gene_symbol 

### ISSUE THREAD

**Issue by asdfjohnny1** [egeulgen/pathfindR#150]
Hello,

I was wondering if it is possible to use ensemble ID instead of gene_symbol when running pathfindR ? 

I am getting some inconsistencies due to the gene symbol!

thank you very much in advance.

all the best,
Johnny

**Comment by egeulgen** [comment]
While there's no built-in data to support other IDs, as outlined [here](https://egeulgen.github.io/pathfindR/articles/intro_vignette.html#analysis-with-custom-gene-sets), you can use custom gene sets and a custom PIN to be able to use pathfindR with another ID type
