### ISSUE TITLE
enrichment_chart() function take too long to respond

### ISSUE THREAD

**Issue by IamYimo** [egeulgen/pathfindR#151]
The enrichment_chart function worked perfectly until yesterday, and then it took a seemingly indefinitely long time to generate the bubble enrichment chart, both for my future enrichment and the enrichment I finished before.

**Comment by IamYimo** [comment]
Hello, yes. Can you give me an email address that I can send my Rdata and script to? Thank you for your rapid response!

**Comment by egeulgen** [comment]
No problem!
you can email me at:
egeulgen [at] gmail [dot] com
