### ISSUE TITLE
Color-blind friendly coloring

### ISSUE THREAD

**Issue by richardcoca** [egeulgen/pathfindR#154]
**Is your feature request related to a problem? Please describe.**
I was wondering whether there is a way to customize the color for up/down regulated genes that is not red or green due to red-green colorblindness.

**Describe the solution you'd like**
A script to change the color

**Comment by egeulgen** [comment]
which visualization function are you referring to? Almost all of the visualization functions return a ggplot object you may manipulate via `scale_fill_manual()` etc.
