### ISSUE TITLE
p value error

### ISSUE THREAD

**Issue by babywing** [egeulgen/pathfindR#165]
Hi! 
I keep getting this error when trying to run pathfinder on my dataset:

output_data <- run_pathfindR(data, gene_sets = "GO-All")
Error in input_testing(input, p_val_threshold) : 
  p values must all be numeric

I have confirmed using str(data) that my p values are numeric. Any idea why this is happening? 

Thanks!

**Comment by RosaLuzia** [comment]
Hi, same happened to me. 
Gene_symbol       logFC       p_val 
"character"   "numeric"   "numeric" . 
Thanks

**Comment by RosaLuzia** [comment]
Thanks, Problem solved :-)
