### ISSUE TITLE
Connection issue with pathfindR

### ISSUE THREAD

**Issue by adrianleverkuehn** [egeulgen/pathfindR#17]
Hi,

when running run_pathfindR(df) I get the warning message: Cannot connect to server. I have disabled the firewall, etc., did not work out.

Best,
D

**Comment by egeulgen** [comment]
Hello,
This may be due to an issue in one of the dependencies of pathfindR or an issue with R itself. Would you mind sharing the entire run's screen output? 
Best,
-E

**Comment by adrianleverkuehn** [comment]
Sure!

> names(data_pathway) <- c("Gene.symbol", "logFC", "adj.P.Val")
> data_pathway <- subset(data_pathway, data_pathway$adj.P.Val > 0)
> output <- run_pathfindR(data_pathway[1:10, ])
## Testing input


The input looks OK


## Processing input. Converting gene symbols, if necessary (and if human gene symbols provied)


Could not find any interactions for 1 (50%) genes in the PIN


## Performing Active Subnetwork Search and Enrichment

Error in { : task 1 failed - "kann Verbindung nicht öffnen"
In addition: Warning messages:
1: In run_pathfindR(data_pathway[1:10, ]) :
  There already is a directory named "pathfindR_Results".
Writing the result to "pathfindR_Results(6)" not to overwrite the previous results.
2: In pathfindR::input_processing(input, p_val_threshold, pin_path,  :
  The gene column was turned into character from factor.

**Comment by egeulgen** [comment]
Even if you only filter for `adj.P.Val > 0`, pathfindR initially filters for `p <= 0.05` by default. Though, we would recommend against it, you can change this threshold by setting `p_val_threshold = 0` when running `run_pathfindR`.

Because the (by default) 10 iterations of subnetwork search + enrichment is in parallel, the error is usually cryptic stating only `task 1 failed`. This error is the same for all of the steps in the parallel loop.

The initial warning states `Could not find any interactions for 1 (50%) genes in the PIN` so the input for active subnetwork search (basically `data_pathway` filtered by `p <= 0.05`) contains only 2 genes (1 was found in the protein-protein interaction network and the other wasn't). Because there is only 1 gene in the input, the active subnetwork search process fails.

I recommend changing the run command to `output <- run_pathfindR(data_pathway[1:10, ], p_val_threshold = 0)`. Meanwhile, I will add a step that checks if the input dataframe is larger than 1 gene.

Best,
-E

**Comment by adrianleverkuehn** [comment]
Sorry, but it is still not running. When I set p_val_threshold = 0, there is "no gene found in the PIN". If I define p_val_threshold = 0.01 there are all genes found in the PIN, however, the subnetwork search fails again due to a connectivity problem.

> output <- run_pathfindR(data_pathway[1:500, ], p_val_threshold = 0.01)
## Testing input


The input looks OK


## Processing input. Converting gene symbols, if necessary (and if human gene symbols provied)


Found interactions for all genes in the PIN


## Performing Active Subnetwork Search and Enrichment

Error in { : task 1 failed - "kann Verbindung nicht öffnen"

**Comment by adrianleverkuehn** [comment]
Sorry, but it is still not running. When I set p_val_threshold = 0, there is "no gene found in the PIN". If I define p_val_threshold = 0.01 there are all genes found in the PIN, however, the subnetwork search fails again due to a connectivity problem.

> output <- run_pathfindR(data_pathway[1:500, ], p_val_threshold = 0.01)
## Testing input


The input looks OK


## Processing input. Converting gene symbols, if necessary (and if human gene symbols provied)


Found interactions for all genes in the PIN


## Performing Active Subnetwork Search and Enrichment

Error in { : task 1 failed - "kann Verbindung nicht öffnen"

**Comment by egeulgen** [comment]
hello @adrianleverkuehn, would you mind sharing the input data (data_pathway) as an RDS file so we can try to reproduce the issue?

**Comment by hernandezvargash** [comment]
Similar issue here. Any help appreciated.
I installed with pak::pkg_install("pathfindR") w/o any issues, but get this error when running the example (output_df <- run_pathfindR(RA_input, p_val_threshold = 0.01)):
Error in download.file(url, t, quiet = TRUE) : 
  cannot open URL 'https://www.kegg.jp/kegg-bin/show_pathway?hsa03040/hsa%3a9879%09white,black/hsa%3a7919%09white,black/hsa%3a6625%09white,black/hsa%3a6626%09white,black/hsa%3a6631%09white,black/hsa%3a8449%09white,black/hsa%3a9785%09white,black/hsa%3a51362%09white,black/hsa%3a58517%09white,black/hsa%3a1659%09white,black/hsa%3a1665%09white,black/hsa%3a1655%09white,black/hsa%3a10915%09white,black/hsa%3a6627%09white,black/hsa%3a6629%09white,black/hsa%3a22827%09%232FEE2F,black/hsa%3a10285%09white,black/hsa%3a84991%09white,black/hsa%3a10523%09white,black/hsa%3a23350%09white,black/hsa%3a27339%09white,black/hsa%3a988%09white,black/hsa%3a10286%09white,black/hsa%3a5356%09white,black/hsa%3a51503%09white,black/hsa%3a56259%09white,black/hsa%3a10084%09white,black/hsa%3a51729%09white,black/hsa%3a22938%09white,black/hsa%3a51645%09white,black/hsa%3a10450%09white,black/hsa%3a151903%09white,black/hsa%3a55696%09white,black/hsa%3a9716%09white,black/hsa%3a26121%09white,black/hsa%3a10465%09white,bla...

**Comment by egeulgen** [comment]
@hernandezvargash this issue was resolved in the development version. Please download the dev version via:

```r
pak::pkg_install("egeulgen/pathfindR")
```

**Comment by hernandezvargash** [comment]
cool, this is working, thanks a lot!

**Comment by lucalvizi** [comment]
Hi, I am having this error when 
> pak::pkg_install("egeulgen/pathfindR")
Error: callr subprocess failed: row names contain missing values

could you help me with that please?

Thank you

**Comment by egeulgen** [comment]
Hey @lucalvizi,
This is an issue with pak. I suggest you create an issue there. Meanwhile you can install pathfindR dev version via devtools:
```r
install.packages("devtools") # if you have not installed "devtools"
devtools::install_github("egeulgen/pathfindR")
```

**Comment by lucalvizi** [comment]
Many thanks!
