### ISSUE TITLE
fold change filtering possibility

### ISSUE THREAD

**Issue by abedkurdi** [egeulgen/pathfindR#179]
Hi there!

I would like to ask if adding a threshold on the log2 fold change (for instance, absolute log2 fold change of 1) before running `run_pathfindR` is acceptable or not.

Thanks in advance!

**Comment by ozanozisik** [comment]
Hello,
Sure, you can apply thresholds to the data and then run pathfindR.
As a note, by default, pathfindR only applies a p-value threshold of 0.05.
Regards.

**Comment by abedkurdi** [comment]
Thanks a lot!
