### ISSUE TITLE
Upcoming changes in ggplot2

### ISSUE THREAD

**Issue by teunbrand** [egeulgen/pathfindR#189]
Hello there,

We have been preparing a new release of ggplot2 and during a reverse dependency check, it became apparent that the prospective ggplot2 3.5.0 would break pathfindR.

The error we encounter is in the `UpSet_plot()` plot function, but we believe the underlying issue might be in the interaction with ggupset package. In any case, it seems the issue is in calculation the resolution for tiles, but ggplot2 itself has no methods to do so for list-input provided via `UpSet_plot()`.

To test the code changes with the release candidate, you can install it with the code below:

```r
remotes::install_github("tidyverse/ggplot2", ref = remotes::github_pull("5592"))
```

The release of ggplot2 3.5.0 is scheduled for the 12th of February. The progress of the release can be tracked in https://github.com/tidyverse/ggplot2/issues/5588. We hope that this reports informs you in a timely manner about upcoming changes.

**Comment by egeulgen** [comment]
Hello @teunbrand,

Thanks for raising this, I've implemented a fix and locally tested that there are no more errors. After the fix is merged in, I'll increment the patch version and submit to CRAN. Just wanted to keep you updated.

**Comment by teunbrand** [comment]
Thank you for the prompt response Ege!
