### ISSUE TITLE
PathfindR not supporting M3 Mac?

### ISSUE THREAD

**Issue by jasoncrucify** [egeulgen/pathfindR#194]
Dear Developer,

we are currently working on a bioinformatic analysis using PathfindR as reference, with a Mac M3, and it is not possible to activate the packages in my Mac, could you debug and explain if it is fixed?

many thanks in advance?

**Comment by egeulgen** [comment]
Hello @jasoncrucify ,
It’s not clear what you mean by “activate”, are you having installation issues? Can you share any errors you receive, also the output of running `sessionInfo()` in R?

**Comment by egeulgen** [comment]
As I understand, you restored from a backup. If so, you wouldn’t be able to load the library that was previously installed for x86_64, you should install it for arm64 (which the installer will handle):
`install.packages("pathfindR")`

if the issue persists, kindly provide more details: steps taken before the issue arose, your R configuration (output of `sessionInfo()`)

**Comment by jasoncrucify** [comment]
Thanks,

Here is the error: 

##############################################################################
Error: package or namespace load failed for ‘pathfindR’:
 .onAttach failed in attachNamespace() for 'pathfindR', details:
  call: check_java_version()
  error: Java version detected but couldn't parse version from The operation couldn’t be completed. Unable to locate a Java Runtime. - Please visit http://www.java.com for information on installing Java. - 
In addition: Warning message:
In system2(java, "-version", stderr = TRUE, stdout = TRUE) :
  running command ''/usr/bin/java' -version 2>&1' had status 1

I tried to uninstall the package and reinstall again following the code provided.

Many thanks for debugging.

Sincerely yours,

**Comment by egeulgen** [comment]
there seems to be an issue with Java installation/R configuration.
Please follow the advice [in this article](https://solutions.posit.co/envs-pkgs/using-rjava/#setup-java-support-in-r) and let me know if that resolves the issue.
Particularly, [this section to reconfigure R](https://solutions.posit.co/envs-pkgs/using-rjava/#reconfigure-r) so that R points to the desired Java installation.
```bash
sudo R CMD javareconf
```

**Comment by jasoncrucify** [comment]
Thanks for your reply
It works now your package after reinstallation of Java :)
Sincerely yours
