### ISSUE TITLE
Using pathfindR with custom gene sets

### ISSUE THREAD

**Issue by alcooj** [egeulgen/pathfindR#2]
Good day, Ege.

I've been trying out pathfindR and, though the documentation on some of the arguments in `run_pathfindR` is still sketchy (I'm new to this so it was not clear to me how to properly tune search method parameters),  I think it's a wonderful package overall.

I was wondering if there is a way to define custom gene sets to run the analysis on. I'm particularly interested in gene sets from the MSigDB collections that do overlap with the currently available gene sets (ex. Reactome, GO, etc.).

**Comment by alcooj** [comment]
Looking forward to it. 
Thanks.

**Comment by egeulgen** [comment]
Hello again @alcooj,

I've just implemented the option to specify a custom gene set. For this, you should:

1. Set the `gene_sets` argument to "Custom"
2. To the `custom_genes` argument, provide a list object whose names are pathway IDs and elements are vectors of gene symbols contained in that pathway.
3. To the `custom_pathways` argument, provide a named vector of pathway names, the names of the vector here are pathway IDs.

I'll hopefully update the wiki to include an example on how to use a custom gene set. In the meanwhile though, feel free to contact about any issue.

Best,
-E

**Comment by alcooj** [comment]
Hello, Ege.

Sorry for just responding now. I haven't checked my GitHub account for quite some time.

I've not worked with gene sets for a while, but I'll be sure to try it out when I get the chance.

Thanks again for all your hard work.
