### ISSUE TITLE
bubble chart

### ISSUE THREAD

**Issue by csantosrocha** [egeulgen/pathfindR#20]
Hi. I'm wondering if we can specify the number or pathways (e.g Top10) to be displayed in the bubble charts

**Comment by YunielFM** [comment]
Hi, I had the same thought, but solved it by getting the resulting object from the pathfindr analysis and customizing it using ggplot2 (filter, shading, coloring).

**Comment by YunielFM** [comment]
Just to be a  bit more specific, the result from the pathfindR is a dataframe that you can save internally in R, with the following columns:
**ID, Pathway, Fold_Enrichment, occurrence, lowest_p, highest_p, Up_regulated, Down_regulated.** You can decide to filter your top10 genes according to some of them (Panther uses the pvalue, but you can chose here also the pathway enrichment as a criterion.). After filtering you will only need to do an easy plot using ggplot2 or your favourite library from the CRAN.

**Comment by egeulgen** [comment]
hey @csantosrocha, there is no argument for selecting top X pathways but you can subset the resulting data frame of `run_pathfindR` and use the subset as the input for `enrichment_chart`, the function for creating the bubble chart
