### ISSUE TITLE
egeulgen, this enhancement does not seem to be working. KEGG diagrams are imported but they do no overlay the input data. Do you have any suggestions on how to fix this?

### ISSUE THREAD

**Issue by k-blenman** [egeulgen/pathfindR#214]
egeulgen, this enhancement does not seem to be working. KEGG diagrams are imported but they do no overlay the input data. Do you have any suggestions on how to fix this?

_Originally posted by @k-blenman in https://github.com/egeulgen/pathfindR/issues/200#issuecomment-2395549364_

**Comment by egeulgen** [comment]
Hi @k-blenman, I haven't had the chance yet but I will look into this

**Comment by egeulgen** [comment]
Hi @k-blenman,
The fixed function is now available in the development version of `pathfindR`, you can install this via:

```r
install.packages("devtools") # if you have not installed "devtools"
devtools::install_github("egeulgen/pathfindR")
```
