### ISSUE TITLE
go_all_genes_description file is not found

### ISSUE THREAD

**Issue by boseb** [egeulgen/pathfindR#27]
Hi,
I am trying to do single gene set enrichment with GO using
enrichment(
            input_genes,
            genes_by_term = pathfindR::go_all_genes,
            term_descriptions = GO_all_terms_df,
            adj_method = "bonferroni",
            enrichment_threshold = 0.05,
            sig_genes_vec,
            background_genes=unlist(go_all_genes)
          ) 

It seems description file "GO_all_terms_df"  is missing.
Please help.
Thanks
Bose

**Comment by egeulgen** [comment]
hey @boseb,

that data frame is an internal object so you can only access it via `pathfindR:::GO_all_terms_df`. However, that is not the term descriptions in the correct format so it needs to be processed as a named vector.

If you want to perform simple ORA using `input_genes` on "GO-All", you should follow below:

```r
library(pathfindR)
go_df <- pathfindR:::GO_all_terms_df
go_all_descriptions <- go_df$GO_term
names(go_all_descriptions) <- go_df$GO_ID

result_df <- enrichment(input_genes = input_genes,
                        genes_by_term = go_all_genes,
                        term_descriptions = go_all_descriptions,
                        adj_method = "bonferroni", # default
                        enrichment_threshold = 0.05, # default
                        sig_genes_vec = input_genes, # because you are only performing ORA
                        background_genes = unique(unlist(go_all_genes))) # or some other "universe" of background genes
```

Hope this helps,
-E
