### ISSUE TITLE
Cannot run example dataset

### ISSUE THREAD

**Issue by nbruse** [egeulgen/pathfindR#28]
Hey, 

It is probably an issue with the installation, but I cannot even execute the run_pathfindr function on the example dataset without getting this error. The progress bar also only shows up after the whole process is done. 

```
> library(pathfindR)
> head(RA_input)
  Gene.symbol      logFC    adj.P.Val
1     FAM110A -0.6939359 3.408699e-06
2      RNASE2  1.3535040 1.008499e-05
3      S100A8  1.5448338 3.466386e-05
4      S100A9  1.0280904 2.262617e-04
5      TEX261 -0.3235994 2.262617e-04
6    ARHGAP17 -0.6919330 2.708081e-04
> RA_output <- run_pathfindR(RA_input)
`n_processes` is set to `iterations` because `iterations` < `n_processes`
There is already a directory named "pathfindR_Results".
Writing the result to "pathfindR_Results(3)" not to overwrite any previous results.
## Testing input
The input looks OK
## Processing input. Converting gene symbols,
          if necessary (and if human gene symbols provided)
Number of genes provided in input: 572
Number of genes in input after p-value filtering: 572

Could not find any interactions for 11 (1.92%) genes in the PIN
Final number of genes in input: 561
## Performing Active Subnetwork Search and Enrichment
## Processing the enrichment results over all iterations
## Annotating involved genes and visualizing enriched terms
Downloading pathway diagrams of 10 KEGG pathways

  |                                                                                                                                                                |   0%Cannot download KGML file for: hsa03040
Here's the original error message:
  |================                                                                                                                                                |  10%Cannot download KGML file for: hsa00190
Here's the original error message:
  |================================                                                                                                                                |  20%Cannot download KGML file for: hsa05012
Here's the original error message:
  |================================================                                                                                                                |  30%Cannot download KGML file for: hsa04932
Here's the original error message:
  |================================================================                                                                                                |  40%Cannot download KGML file for: hsa03410
Here's the original error message:
  |================================================================================                                                                                |  50%Cannot download KGML file for: hsa05010
Here's the original error message:
  |================================================================================================                                                                |  60%Cannot download KGML file for: hsa04064
Here's the original error message:
  |================================================================================================================                                                |  70%Cannot download KGML file for: hsa05016
Here's the original error message:
  |================================================================================================================================                                |  80%Cannot download KGML file for: hsa04714
Here's the original error message:
  |================================================================================================================================================                |  90%Cannot download KGML file for: hsa03013
Here's the original error message:
  |================================================================================================================================================================| 100%
Saving colored pathway diagrams of 0 KEGG pathways

Error in utils::txtProgressBar(min = 0, max = length(pw_vis_list), style = 3) : 
  must have 'max' > 'min'
```

Is this a known error?

Thank you for your time.

**Comment by egeulgen** [comment]
None of the KEGG pathways could be downloaded, please check your internet connection. If visualization is not necessary, set `visualize_enriched_terms=FALSE`. 

The error was: because no pathway diagrams could be downloaded, there were 0 diagrams to color. Because the progress bar for coloring requires the minimum and maximum (both 0 in this case), it failed.

The latest commit fixes this issue. If you'd like, please download the latest development version via:

```r
install.packages("pak") # if you have not installed "pak"
pak::pkg_install("egeulgen/pathfindR")
```

**Comment by alymatz** [comment]
Hi! 
I am having the same issue as discussed above, I installed the latest development version as suggested and there has been no change. My internet is connected and strong and I restarted my computer as well. I am using my own data for this analysis. I did wish to visualize the results. 
Thank you for your consideration! 
Sincerely, 
Alyssa

**Comment by kratzera** [comment]
Hej,
I try to visualise KEGG pathways of my data, but it gives me the following error:
Here's the original error message:
'color.pathway.by.objects()' failed to extract KEGG image path from response.
Cannot download PNG file: NA
Here's the original error message:
invalid 'url' argument
I get that for all pathways.

Here is my data I try to run:
 GenesUpDownP1_KEGG_processed <- input_processing(GenesUpDownP1.df, pin_name_path="KEGG",convert2alias = TRUE)
  visualize_terms(
    result_df = GenesUpDownP1_GO_KEGG,
    input_processed = GenesUpDownP1_KEGG_processed,
    hsa_KEGG = TRUE, pin_name_path = "KEGG"
  )

Thank you for your help!
H

**Comment by egeulgen** [comment]
Can you share the data you use for this (GenesUpDownP1_KEGG_processed and GenesUpDownP1_GO_KEGG) as RDS files?Best,-EOn 5 Jun 2023, at 22:41, kratzera ***@***.***> wrote:﻿
Hej,
I try to visualise KEGG pathways of my data, but it gives me the following error:
Here's the original error message:
'color.pathway.by.objects()' failed to extract KEGG image path from response.
Cannot download PNG file: NA
Here's the original error message:
invalid 'url' argument
I get that for all pathways.
Here is my data I try to run:
GenesUpDownP1_KEGG_processed <- input_processing(GenesUpDownP1.df, pin_name_path="KEGG",convert2alias = TRUE)
visualize_terms(
result_df = GenesUpDownP1_GO_KEGG,
input_processed = GenesUpDownP1_KEGG_processed,
hsa_KEGG = TRUE, pin_name_path = "KEGG"
)
Thank you for your help!
H

**Comment by kratzera** [comment]
Hej there,
Thank you for your reply. I am still very new to this, but I manage bit by bit to work with it and I think your script is great. It’s probably sthg small that I cannot see that is wrong.
Please find attached the files you asked for:

Best and thanks,
Heidi

**Comment by egeulgen** [comment]
hello again, I think attachments via mail don't work, can you try sending from github web?

**Comment by kratzera** [comment]
hello again, sorry for the late reply. I ran into more problems in the last weeks. I updated my Rstudio to Version 2023.06.0+421 and R to 4.3.1  and now I get a fatal error when I try to run pathfindR. Any recommendations/suggestions?
Thanks
