### ISSUE TITLE
cannot load pathfindR

### ISSUE THREAD

**Issue by safrikDut** [egeulgen/pathfindR#29]
Hi! after loading pathfindR:
> library("pathfindR")
##############################################################################
                        Welcome to pathfindR!

Please cite the article below if you use pathfindR in published reseach:

Ulgen E, Ozisik O, Sezerman OU. 2019. pathfindR: An R Package for Comprehensive
Identification of Enriched Pathways in Omics Data Through Active Subnetworks.
Front. Genet. doi:10.3389/fgene.2019.00858

##############################################################################
Error: package or namespace load failed for ‘pathfindR’:
 .onAttach failed in attachNamespace() for 'pathfindR', details:
  call: system2(java, "-version", stderr = TRUE, stdout = TRUE)
  error: '""' not found

Is it an issue with the R version? (3.6.2)

**Comment by egeulgen** [comment]
It seems that you don't have java installed on your system. Please download and install java from: https://www.java.com/en/

**Comment by Elseedy28** [comment]
i have the same problem and i downloaded and i still have the same problem 

elcome to pathfindR!

Please cite the article below if you use pathfindR in published reseach:

Ulgen E, Ozisik O, Sezerman OU. 2019. pathfindR: An R Package for Comprehensive
Identification of Enriched Pathways in Omics Data Through Active Subnetworks.
Front. Genet. doi:10.3389/fgene.2019.00858

##############################################################################
Error: le chargement du package ou de l'espace de noms a échoué pour ‘pathfindR’ :
.onAttach a échoué dans attachNamespace() pour 'pathfindR', détails :
  appel : fetch_java_version()
  erreur : Java version not detected. Please download and install Java from “https://www.java.com/en/”
>

**Comment by egeulgen** [comment]
Please configure  `HOME` and `JAVA_HOME`, as suggested [here](https://github.com/egeulgen/pathfindR/wiki/Installation#configuration-of-java-on-windows)
