### ISSUE TITLE
Clustering error due to NAs introduced during correlation

### ISSUE THREAD

**Issue by alcooj** [egeulgen/pathfindR#3]
Good day, Ege.

I would encounter from time to time the following error message:
![image](https://user-images.githubusercontent.com/12235998/42135441-a77c0690-7d10-11e8-8500-8b84c8804578.png)

Judging from the message, it seems that `run_pathfindR` is creating data that results in NAs when running `choose_clusters`. 

My current workaround is to run the code several times and one of the results turn up error-free. But given the time to run the pathfindR code and this trial-and-error approach, I was hoping if there is a better way of doing it.

Thanks.

**Comment by egeulgen** [comment]
hey @alcooj can you send me your input file so that I can reproduce the error?

**Comment by alcooj** [comment]
I guess it should be fine if I censor the labels. Maybe I should email the data and code I used?

**Comment by egeulgen** [comment]
resolved
