### ISSUE TITLE
csv file problem

### ISSUE THREAD

**Issue by safrikDut** [egeulgen/pathfindR#30]
Hi! I´m having problems with reading the .csv file upon loading pathfindR. 
> read.csv (file)
the environment shows me 1233 obs of 3 variables

or

>glimpse (file)

Observations: 1,522
Variables: 3
$ gene_symbol <fct> IFNL1, IFNL3, IFNL2, IFNL4, EGR2, IFNB1, IFI44L, XAF1, GBP4, CXCL10, CCL5...
$ logFC       <dbl> 13.36986141, 13.00849043, 12.87799430, 11.50148222, 11.09193259, 10.97011...
$ pvalue      <dbl> 1.4602e-28, 5.9649e-27, 2.3935e-26, 3.6240e-21

but when using 

suppressPackageStartupMessages(library(pathfindR))
> data(file)
> head(file)

the environment shows 1233 obs of 1 variable and the table shows one one column with altogether:
gene_symbol,logFC,pvalue

Could I get the file RA_input.csv as example to compare the format?

**Comment by egeulgen** [comment]
can you share the `file`? You may save the example input yourself via `write.csv(RA_input, "file.txt")`.

**Comment by safrikDut** [comment]
Here is the file!

[KAN1_allR.zip](https://github.com/egeulgen/pathfindR/files/4170450/KAN1_allR.zip)

I used Excel 2016 and saved it as .csv.

**Comment by egeulgen** [comment]
I cannot replicate your issue. Perhaps, it is related to another package or your OS? Is it still persisting?
I am closing this issue as it does not seem to be related to pathfindR
