### ISSUE TITLE
wget command not found

### ISSUE THREAD

**Issue by aj12aj** [egeulgen/pathfindR#32]
Hi,

I've been getting this issue of the wget command not found. Is there a way to fix this?  tried installing the latest version too using this line: pak::pkg_install("egeulgen/pathfindR") but it gave me the same error.

> > output_df <- run_pathfindR(input_df)
> ## Testing input
> The input looks OK
> ## Processing input. Converting gene symbols,
>           if necessary (and if human gene symbols provided)
> Number of genes provided in input: 603
> Number of genes in input after p-value filtering: 603
> Could not find any interactions for 45 (7.59%) genes in the PIN
> Final number of genes in input: 548
> ## Performing Active Subnetwork Search and Enrichment
> ## Processing the enrichment results over all iterations
> ## Annotating involved genes and visualizing enriched terms
> Downloading pathway diagrams of 10 KEGG pathways
> 
>   |                                                                        |   0%sh: wget: command not found
> Cannot download KGML file for: hsa03050
> Here's the original error message:
>   |=======                                                                 |  10%sh: wget: command not found
> Cannot download KGML file for: hsa00030
> Here's the original error message:
>   |==============                                                          |  20%sh: wget: command not found
> Cannot download KGML file for: hsa04012
> Here's the original error message:
>   |======================                                                  |  30%sh: wget: command not found
> Cannot download KGML file for: hsa05161
> Here's the original error message:
>   |=============================                                           |  40%sh: wget: command not found
> Cannot download KGML file for: hsa05100
> Here's the original error message:
>   |====================================                                    |  50%sh: wget: command not found
> Cannot download KGML file for: hsa05169
> Here's the original error message:
>   |===========================================                             |  60%sh: wget: command not found
> Cannot download KGML file for: hsa04960
> Here's the original error message:
>   |==================================================                      |  70%sh: wget: command not found
> Cannot download KGML file for: hsa04714
> Here's the original error message:
>   |==========================================================              |  80%sh: wget: command not found
> Cannot download KGML file for: hsa00190
> Here's the original error message:
>   |=================================================================       |  90%sh: wget: command not found
> Cannot download KGML file for: hsa05205
> Here's the original error message:
>   |========================================================================| 100%
> Saving colored pathway diagrams of 0 KEGG pathways
> 
> Error in utils::txtProgressBar(min = 0, max = length(pw_vis_list), style = 3) : 
>   must have 'max' > 'min'
> In addition: There were 13 warnings (use warnings() to see them)

Thanks for the help!

**Comment by egeulgen** [comment]
You need to have wget installed on your system.
Alternatively, you may use `visualize_enriched_terms = TRUE` for not visualizing the enriched terms.

**Comment by aj12aj** [comment]
It worked now! Thank you!

**Comment by harish0201** [comment]
I'm using the docker image as I'm encountering dependency hell while installing this on centos, but doesn't the docker image have wget installed in it?

Alternatively, is there a way to run this directly through the shell?

Currently, I'm using it like this: `docker run -v $PWD:$PWD -it egeulgen/pathfindr`

**Comment by egeulgen** [comment]
@harish0201 
Sorry, I updated the docker images so that they have wget installed.

I'm doing the same to use it, couldn't find another way yet but I'll let you know if I can find anything more practical

**Comment by harish0201** [comment]
Thanks, should I just pull the image again?

**Comment by egeulgen** [comment]
Yes. I would suggest the dev image

-E

**Comment by harish0201** [comment]
Thanks, it worked!
