### ISSUE TITLE
term_gene_heatmap(), UpSet_plot() functions are not working

### ISSUE THREAD

**Issue by choisama** [egeulgen/pathfindR#33]
Hello, 
When will pathfindR version 1.5.0.9004 will be release to R cran? I tried to download latest version by using 
`#install.packages("remotes")
#remotes::install_github("egeulgen/pathfindR")`
but only downloaded v1.4.2 
because i wanna use term_gene_heatmap(), UpSet_plot() functions to visualize data

Thank you

**Comment by egeulgen** [comment]
hello,

we do not plan to release 1.5 soon. You can try and download the dev version using:
```r
install.packages("pak") # if you have not installed "pak"
pak::pkg_install("egeulgen/pathfindR")
```
I think remotes installs the latest release on github.
Hope this helps,
-E

**Comment by egeulgen** [comment]
has this resolved your issue?

**Comment by choisama** [comment]
Good afternoon,

Yes it worked well. Thanks for your help.

**Comment by choisama** [comment]
thank you it worked so well.
