### ISSUE TITLE
Same error message, suggested fix did not work 

### ISSUE THREAD

**Issue by alymatz** [egeulgen/pathfindR#38]
Hi! 
I am having the same error as discussed previously on Jan 28: 
"Error in utils::txtProgressBar(min = 0, max = length(pw_vis_list), style = 3) : 
  must have 'max' > 'min'"
In response to the previous poster, you suggested downloading a new update. I did so and restarted my computer but there was no change. I am connected to the internet and my connection is strong. I would like to visualize my results if possible. 
Thank you for your consideration! 
Sincerely, 
Alyssa

**Comment by egeulgen** [comment]
Hey @alymatz,
Have you tried to download the latest development version? This can be achieved via pak:

```r
install.packages("pak") # if you have not installed "pak"
pak::pkg_install("egeulgen/pathfindR")
```

This issue was fixed. If installing the latest development version does not work, please provide the script you run and the exact error you get.
Best,
-E

**Comment by alymatz** [comment]
Hi E, I installed the latest version and still got the same error. Here is more of the script, if more is needed please let me know! I am very new to R. 

> output<-run_pathfindR(m)
There is already a directory named "pathfindR_Results".
Writing the result to "pathfindR_Results(8)" not to overwrite any previous results.
## Testing input
The input looks OK
## Processing input. Converting gene symbols,
          if necessary (and if human gene symbols provided)
Number of genes provided in input: 119
Number of genes in input after p-value filtering: 79
pathfindR cannot handle p values < 1e-13. These were changed to 1e-13

Could not find any interactions for 23 (29.11%) genes in the PIN
Final number of genes in input: 56
## Performing Active Subnetwork Search and Enrichment
## Processing the enrichment results over all iterations
## Annotating involved genes and visualizing enriched terms
Downloading pathway diagrams of 10 KEGG pathways

  |                                                                                                          |   0%Cannot download KGML file for: hsa04062
Here's the original error message:
  |===========                                                                                               |  10%Cannot download KGML file for: hsa04630
Here's the original error message:
  |=====================                                                                                     |  20%Cannot download KGML file for: hsa04061
Here's the original error message:
  |================================                                                                          |  30%Cannot download KGML file for: hsa04620
Here's the original error message:
  |==========================================                                                                |  40%Cannot download KGML file for: hsa05145
Here's the original error message:
  |=====================================================                                                     |  50%Cannot download KGML file for: hsa05235
Here's the original error message:
  |================================================================                                          |  60%Cannot download KGML file for: hsa04668
Here's the original error message:
  |==========================================================================                                |  70%Cannot download KGML file for: hsa04657
Here's the original error message:
  |=====================================================================================                     |  80%Cannot download KGML file for: hsa05164
Here's the original error message:
  |===============================================================================================           |  90%Cannot download KGML file for: hsa04621
Here's the original error message:
  |==========================================================================================================| 100%
Saving colored pathway diagrams of 0 KEGG pathways

Error in utils::txtProgressBar(min = 0, max = length(pw_vis_list), style = 3) : 
  must have 'max' > 'min'
In addition: Warning message:
In pathfindR::input_processing(input, p_val_threshold, pin_path,  :
  The gene column was turned into character from factor.

**Comment by egeulgen** [comment]
ok I think `pak` is installing the latest release on github. Do you mind installing the development via devtools:

```r
devtools::install_github("egeulgen/pathfindR")
```

**Comment by alymatz** [comment]
Yes! Thank you!! 
-Alyssa
