### ISSUE TITLE
term_gene_heatmap(output_df) doesnt work without downregulated genes

### ISSUE THREAD

**Issue by AlexandrePelletier** [egeulgen/pathfindR#39]
Hello,
the function `term_gene_heatmap(output_df)` doesn't work with my methylation data without FC in input.
 the error : 
"Error in names(down_genes) <- result_df[, ID_column] : 
  'names' attribute [10] must be the same length as the vector [0]"

I install the latest developmental version. (with pak)

Best

**Comment by egeulgen** [comment]
Hello,
I fixed the issue in the latest commit. You may install the latest dev version via pak

**Comment by AlexandrePelletier** [comment]
thank you for your quick reply !
