### ISSUE TITLE
how to use pathfindR for mouse data?

### ISSUE THREAD

**Issue by steffenheyne** [egeulgen/pathfindR#4]
Hi,
I would like to use your package for mouse data? It seems all is fixed to human gene symbols etc.

Would it be possible to replace the appropriate objects like 
pathfindR::reactome_genes
pathfindR::kegg_pathways

with the mouse versions and the proceed as usual?

I think you should provide at least the option to use also mouse in addition to human!
thanks,
steffen

**Comment by egeulgen** [comment]
Hey, if you can do so, replacing the objects `kegg_genes` and `kegg_pathways` should work. 
The package was conceived with human applications as a priority but you're absolutely right, I'll try to add the option to use mouse and rat PIN and KEGG pathways in the next release.

**Comment by egeulgen** [comment]
Hello again, 

To keep the package size small, we'll only keep the current (human) PINs and gene sets for now. I do have a fix for your problem though:

There was already the option to specify a custom PIN. I've just implemented the option to specify a custom gene set. For this, you should:

1. Set the `gene_sets` argument to "Custom"
2. To the `custom_genes` argument, provide a list object whose names are pathway IDs and elements are vectors of gene symbols contained in that pathway.
3. To the `custom_pathways` argument, provide a named vector of pathway names, the names of the vector here are pathway IDs.

This makes it possible to replace the default gene set data.

Hope it's helpful,
Best,
-E

**Comment by steffenheyne** [comment]
thanks, I'll try!
Regarding general support of other organisms, there are some R/Bioconductor packages like Biomart or AnnotationDbi etc that can be used to convert Human EntrezIDs eg for MSigDB. KEGG already has some interface and package to download organsim specific versions of KEGG pathways.

**Comment by egeulgen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [vignette for non-human organisms](https://trello.com/c/l2HbHr4y/73-vignette-for-non-human-organisms)

**Comment by shehroz-m** [comment]
hey @steffenheyne have you had any success with using pathfindR with mouse data? If so, I would be glad to know how you managed!

thanks,
Shehroz
