### ISSUE TITLE
unable to install developed version

### ISSUE THREAD

**Issue by Rahel14350** [egeulgen/pathfindR#42]
**Describe the bug**

**To Reproduce**
1. Prepare input as '...'
2. Run the following function: '....'
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS, Windows, Linux]
 - Version [e.g. 10.14.5]

** R Session Information:**
Please provide the R session information (by running `sessionInfo()`)

**Additional context**
Add any other context about the problem here. While pathfindR is an R package, the active subnetwork search functionality is written in Java. If you suspect any issue regarding java please provide your Java version (by running `java --version`)

**Comment by egeulgen** [comment]
You forgot to fill in the template.

What command are you trying to install the development version?

either `devtools` or `pak` should work:
```r
install.packages("devtools") # if you have not installed "devtools"
devtools::install_github("egeulgen/pathfindR")

# OR

install.packages("pak") # if you have not installed "pak"
pak::pkg_install("pathfindR")
```

**Comment by Rahel14350** [comment]
Dear PathfindR team,
I did install the source version and I got the error regarding:
```
Error in download.file(url, t, quiet = TRUE) : 
  cannot open URL 'https://www.kegg.jp/kegg-bin/show_pathway?hsa05202/hsa%3a2130%09white,black/hsa%3a2313%09white,black/hsa%3a2078%09white,black/hsa%3a2115%09white,black/hsa%3a2118%09white,black/hsa%3a54738%09white,black/hsa%3a466%09white,black/hsa%3a7490%09white,black/hsa%3a8013%09white,black/hsa%3a2521%09white,black/hsa%3a1649%09white,black/hsa%3a5077%09white,black/hsa%3a2308%09white,black/hsa%3a5081%09white,black/hsa%3a6760%09white,black/hsa%3a79058%09white,black/hsa%3a7030%09white,black/hsa%3a4609%09white,black/hsa%3a3398%09white,black/hsa%3a9915%09white,black/hsa%3a472%09white,black/hsa%3a5154%09white,black/hsa%3a3560%09white,black/hsa%3a8938%09white,black/hsa%3a7102%09white,black/hsa%3a4291%09white,black/hsa%3a5468%09white,black/hsa%3a4233%09white,black/hsa%3a2321%09white,black/hsa%3a26471%09white,black/hsa%3a1026%09%235FDE5F,black/hsa%3a3486%09white,black/hsa%3a7048%09white,black/hsa%3a3479%09%238ECE8E,black/hsa%3a1051%09white,black/hsa%3a3569%09white,black/hsa%3a64332%0
```
and I see from another issue that you suggested  to reinstall the development version of package but I get this error:
```
> pak::pkg_install("egeulgen/pathfindR")
cli message statuscli message status_updatecli message status_updatecli message status_updatecli message status_updatecli message                                                                                 s_clear
→ Will update 1 packages:
  egeulgen/pathfindR
→ Will not update 110 packages.
→ Will download 1 packages with unknown size.
? Do you want to continue (Y/n) Y
ℹ Building pathfindR 1.5.0.9007                                                 
✔ Built pathfindR 1.5.0.9007 [17.4s]                                            
Error: callr subprocess failed: Failed to move installed package at '/usr/lib64/R/library/pathfindR'

```
Would you please help me here (I reinstalled callr and many other packages but it didn't work).
My system is centOS 7.0 and the R version is 3.6 
sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
loaded via a namespace (and not attached):
[1] processx_3.4.1 compiler_3.6.0 R6_2.4.1       tools_3.6.0    crayon_1.3.4  
[6] callr_3.4.3    ps_1.3.0       pak_0.1.2      tcltk_3.6.0   

Many thanks in advance,
Kind Regards,
Rahel

**Comment by egeulgen** [comment]
dear @Rahel14350,

Please install the development version via `devtools` instead of `pak`:

```r
install.packages("devtools") # if you have not installed "devtools"
devtools::install_github("egeulgen/pathfindR")
```

**Comment by Rahel14350** [comment]
Thanks a lot, it works!

**Comment by egeulgen** [comment]
no problem
