### ISSUE TITLE
Heatmap color not showing up?

### ISSUE THREAD

**Issue by ahdee** [egeulgen/pathfindR#43]
Hi, I'm using version.  pathfindR_1.5.0.9007

When I tried this example the heatmap plots however there is no color associated with logfold change 

`pathfindR::term_gene_heatmap(RA_output)`

Interestingly, the upset plot shows color for the default heatmap, however, the log fold color scheme is discrete, just what is up or down and not a gradient. Any chance to get it to plot with a continuous gradient color scheme instead? 

here is a picture of the upset plot. 

![dFKKdZJ 1](https://user-images.githubusercontent.com/9808122/81434397-ef687900-911a-11ea-8894-14c33282cc2c.png)

thanks!

**Comment by egeulgen** [comment]
in `term_gene_heatmap()`, if you supply the input data frame (i.e. the input for `run_pathfindR()`), the visualization of the heatmap with continuous color scheme is produced:
```r
term_gene_heatmap(result_df = RA_output, 
                  genes_df = RA_input)
```

same with `UpSet_plot()`:
```r
UpSet_plot(result_df = RA_output, 
           genes_df = RA_input)
```
