### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by AmbroiseGecko** [egeulgen/pathfindR#44]
Hi there, I tried to run PathFindR recently and whichever dataset I use, I obtain the following error messages at the end:

Is it possible to know what is going on?
Thank you!!

  |                                                                                                                                     |   0%Cannot download KGML file for: hsa03010
Here's the original error message:
  |=============                                                                                                                        |  10%Cannot download KGML file for: hsa03040
Here's the original error message:
  |===========================                                                                                                          |  20%Cannot download KGML file for: hsa04110
Here's the original error message:
  |========================================                                                                                             |  30%Cannot download KGML file for: hsa00190
Here's the original error message:
  |=====================================================                                                                                |  40%Cannot download KGML file for: hsa05203
Here's the original error message:
  |==================================================================                                                                   |  50%Cannot download KGML file for: hsa05130
Here's the original error message:
  |================================================================================                                                     |  60%Cannot download KGML file for: hsa04218
Here's the original error message:
  |=============================================================================================                                        |  70%Cannot download KGML file for: hsa04141
Here's the original error message:
  |==========================================================================================================                           |  80%Cannot download KGML file for: hsa05169
Here's the original error message:
  |========================================================================================================================             |  90%Cannot download KGML file for: hsa04810
Here's the original error message:
  |=====================================================================================================================================| 100%
Saving colored pathway diagrams of 0 KEGG pathways

Error in utils::txtProgressBar(min = 0, max = length(pw_vis_list), style = 3) : 
  must have 'max' > 'min'
In addition: Warning message:
In pathfindR::input_processing(input, p_val_threshold, pin_path,  :
  The gene column was turned into character from factor.

**Comment by egeulgen** [comment]
please install and try with the latest development version:

```r
install.packages("devtools") # if you have not installed "devtools"
devtools::install_github("egeulgen/pathfindR")
```

**Comment by egeulgen** [comment]
@AmbroiseGecko has the development version resolved your issue?

**Comment by AmbroiseGecko** [comment]
@egeulgen . Thanks, I just tried and yes it works beautifully. Thanks a lot!
