### ISSUE TITLE
Cluster setup failed.

### ISSUE THREAD

**Issue by drFDC** [egeulgen/pathfindR#45]
This is more a bug report for parallel, but I have a (temp) solution that works.

On OSX with R4.0.0 I get the following error with pathfindR:

Cluster setup failed. 7 of 7 workers failed to connect.
Called from: makePSOCKcluster

A temporal solution is to put this in your .Rprofile:

## Revert to 'sequential' setup of PSOCK cluster in RStudio Console on macOS and R 4.0.0
if (Sys.getenv("RSTUDIO") == "1" && !nzchar(Sys.getenv("RSTUDIO_TERM")) && 
    Sys.info()["sysname"] == "Darwin" && getRversion() == "4.0.0") {
  parallel:::setDefaultClusterOptions(setup_strategy = "sequential")
}

I don't know if this is the right place to post this...

**Comment by egeulgen** [comment]
I'll look into this and try to find a permanent solution
