### ISSUE TITLE
Installation issue: Java

### ISSUE THREAD

**Issue by zinagood** [egeulgen/pathfindR#49]
**Describe the bug**
Dear Ege,

My apologies for not checking the R version previously. I updated R, R Studio, and installed all dependencies, including Java 14, for the pathfindR. However, I still have installation issues. I attempted to use CRAN, pak, or GitHub, or source install, as described on your website. However, this failed each time. This time the issue appears to be with parsing the Java version (error: Java version detected but couldn't parse version from: java version "14" 2020-03-17; details below). Perhaps the issue is with 'check_java_version()' function? Please, let me know how to proceed.

Thanks!
Zina

**To Reproduce**
1. install.packages("pathfindR")

installing the source package ‘pathfindR’

trying URL 'https://cran.rstudio.com/src/contrib/pathfindR_1.5.0.tar.gz'
Content type 'application/x-gzip' length 3355703 bytes (3.2 MB)
==================================================
downloaded 3.2 MB

* installing *source* package ‘pathfindR’ ...
** package ‘pathfindR’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘pathfindR’:
 .onAttach failed in attachNamespace() for 'pathfindR', details:
  call: check_java_version()
  error: Java version detected but couldn't parse version from: java version "14" 2020-03-17
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/pathfindR’
Warning in install.packages :
  installation of package ‘pathfindR’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/fn/mhn7pp8s3yj7cng14ywkzyx40000gn/T/Rtmp9Cdbk7/downloaded_packages’

**Expected behavior**
Package installed successfully.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: Catalina 10.15.4

** R Session Information:**
R version 4.0.1 (2020-06-06)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.4

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] prettyunits_1.1.1   pak_0.1.2           ps_1.3.3            fansi_0.4.1        
 [5] digest_0.6.25       crayon_1.3.4        assertthat_0.2.1    rappdirs_0.3.1     
 [9] R6_2.4.1            lifecycle_0.2.0     magrittr_1.5        pillar_1.4.4       
[13] rlang_0.4.6         cli_2.0.2           uuid_0.1-4          curl_4.3           
[17] rstudioapi_0.11     callr_3.4.3         vctrs_0.3.1         ellipsis_0.3.1     
[21] filelock_1.0.2      pkgcache_1.0.7      tools_4.0.1         glue_1.4.1         
[25] compiler_4.0.1      processx_3.4.2      pkgconfig_2.0.3     BiocManager_1.30.10
[29] tibble_3.0.1       

**Additional context**
(base) Zinaidas-MacBook-Pro:~ zinaida$ java --version
java 14 2020-03-17
Java(TM) SE Runtime Environment (build 14+36-1461)
Java HotSpot(TM) 64-Bit Server VM (build 14+36-1461, mixed mode, sharing)

**Comment by egeulgen** [comment]
Dear @zinagood,

We had trouble parsing the version for java "14", which I fixed. Please try to install the latest development version:

```r
install.packages("devtools") # if you have not installed "devtools"
devtools::install_github("egeulgen/pathfindR")
```
