### ISSUE TITLE
pathfindR mouse

### ISSUE THREAD

**Issue by rvaldes** [egeulgen/pathfindR#5]
Is there any possibility to run pathfindR for mouse data?

Thanks

Rafa

**Comment by egeulgen** [comment]
hey Rafa,

There was already the option to specify a custom PIN and as of the latest development version, there is an option to specify custom gene sets. For this, you should:

1. Set the `gene_sets` argument to "Custom"
2. To the `custom_genes` argument, provide a list object whose names are pathway IDs and elements are vectors of gene symbols contained in that pathway.
3. To the `custom_pathways` argument, provide a named vector of pathway names, the names of the vector here are pathway IDs.

You can use this feature with the latest development version. See [here](https://github.com/egeulgen/pathfindR/wiki/Installation#from-github-development) for installation of the development version.

Best,
-E

**Comment by egeulgen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [vignette for non-human organisms](https://trello.com/c/l2HbHr4y/73-vignette-for-non-human-organisms)
