### ISSUE TITLE
p-adjusted in the output of pathfindR

### ISSUE THREAD

**Issue by ManarRashad** [egeulgen/pathfindR#66]
After getting the output of pathfindR, I found lowest p value and highest p value but not find p adjusted

I hope this to be added on the output.
till this moment, what should I do to get the p adjusted for each pathway?
What I thought to use the p.adjust function in R 
p.adjust(pvalue,method = "fdr")

Is this right or not? and if not what should I do?

**Comment by ozanozisik** [comment]
Dear Manar Rashad,
Those p-values are already adjusted. The reason of lowest and highest p-value columns is, same term can be enriched in different iterations in different active subnetworks giving different p-values.
Regards,
Ozan
