### ISSUE TITLE
gene_sets vs. pin_name_path

### ISSUE THREAD

**Issue by ManarRashad** [egeulgen/pathfindR#67]
Dear,
I read the paper and it is very helpful but I confused on the following questions
First: what is the difference between the 2 parameters gene_sets and pin_name_path ?
Second: Is it possible to let the gene_sets = KEGG and also the pin_name_path=KEGG or they should be different ?
Third: on which criteria I should use KEGG for example for pin_name_path not Biogrid ? or it depends on the results ?

Thanks in advance

**Comment by ozanozisik** [comment]
Dear Manar Rashad,
From the documentation (https://cran.r-project.org/web/packages/pathfindR/pathfindR.pdf):
gene_sets: Name  of  the  gene  sets  to  be  used  for  enrichment  analysis.   Available  genesets  are  "KEGG",  "Reactome",  "BioCarta",  "GO-All",  "GO-BP",  "GO-CC", GO-MF", "cell_markers", "mmu_KEGG" or "Custom". If "Custom", the arguments custom_genes and custom_descriptions must be specified. (Default ="KEGG")

pin_name_path: Name  of  the  chosen  PIN  or  path/to/PIN.sif.   If  PIN  name,  must  be  one  of c("Biogrid", "STRING", "GeneMania", "IntAct", "KEGG", "mmu_STRING"). If path/to/PIN.sif, the file must comply with the PIN specifications.  (Default ="Biogrid")

One is the name of the pathways/terms list used for enrichment, other is the protein interaction network to be used for active subnetwork search.

You can set both to KEGG but by doing this 
- You will limit the interactions to the interactions in KEGG
- You will use the same information for both search and enrichment
This will increase the chance of getting significant KEGG pathways thay may not present the intrinsic property of your input. 
If you do not have a specific purpose, I would suggest using a different PIN.
