### ISSUE TITLE
Microbiome shotgun genes enrichment 

### ISSUE THREAD

**Issue by mariam50411** [egeulgen/pathfindR#70]
Greetings, 

Thanks for developing this package.

I know that we could use a customize a gene set with the specific organism of interest, however, I couldn't find any way to analyze microbiome related data. I have gut and nares microbiome KOs converted into gene symbols so could I use the default parameters as they already live inside the human or will this affect the reliability of the sub-networks? 

Thanks in advance
Mariam Oweda

**Comment by egeulgen** [comment]
Hey @mariam50411,

I do not have any experience with microbiome related data. I'm not sure if you're genes belong to human or microbiome. However, if you're interested in the alterations in human pathways, I would use the default PIN and gene sets. If you're interested in the alterations in microbiome pathways, I would provide a custom PIN and gene sets data.

Hope this helps,
Best,
-E
