### ISSUE TITLE
KEGG gene mapping bug

### ISSUE THREAD

**Issue by psterk** [egeulgen/pathfindR#8]
When multiple genes map to the same gene in a KEGG pathway (e.g. EIF3C and EIF3E both map to eIF3 in hsa03013 - RNA transport), the gene with the lowest p-value (and highest fold change?) should appear in the pathway image generated by pathview. I have in my input data the following:

Gene.name     log2(FC)    adj.P.val
EIF3C	0.529	0.0005
EIF3E	0.1	        0.049

The gene name that appears in the graphic is EIF3E, but the intentensity of the red colour corresponds with the that of EIF3C. If I remove EIF3E, the name EIF3C appears with the same colour intensity. If I remove EIF3C, EIF3E appears with a reduced intensity. This looks like a bug to me.

**Comment by ozanozisik** [comment]
Hi, thank you for your interest and bug report. This issue is partly related to pathview and partly related to the choice of representation in KEGG, in pathview they might have chosen not to change the representational gene name.
Regards.
