### ISSUE TITLE
Mouse database

### ISSUE THREAD

**Issue by pekjoonwu** [egeulgen/pathfindR#80]
Hey,

Thanks for developing this wonderful tool! I am wondering if you guys would update the package with Mouse terms and pathways?

Thanks.

**Comment by egeulgen** [comment]
Hey,
Thanks for your kind appraisal. The mouse-related data are already in the package and can be used follows:

```r
mmu_output <- run_pathfindR(input = myeloma_input,
                            convert2alias = FALSE,
                            gene_sets = "mmu_KEGG",
                            pin_name_path = "mmu_STRING")
```

For other organisms, see [this related vignette](https://egeulgen.github.io/pathfindR/articles/non_hs_analysis.html)
