### ISSUE TITLE
R session aborted, R encountered a fatal error

### ISSUE THREAD

**Issue by caonetto** [egeulgen/pathfindR#88]
Hi, first of all thanks for creating this package!
I am encountering a fatal error everytime I try to run pathfindR with the plot_enrichment_chart = TRUE option. I am using my own custom gene set (Saccharomyces cerevisiae) and it all runs smoothly as long as I dont try to plot the enrichment charts. I am not seeing any errors in the console prior to R freezing completely which forces me to terminate the session. 
Any ideas what could be going on??

Thanks

**Comment by egeulgen** [comment]
hey,
Thanks, glad you enjoy the package.
This might be related to an issue with ggplot2 or maybe an R issue in general (see https://github.com/rstudio/rstudio/issues/9373, maybe try fixes suggested there?)

Could you share your `sessionInfo()`?

**Comment by caonetto** [comment]
Thanks, fixed with the update of Rstudio!
