### ISSUE TITLE
filtering the input genelist

### ISSUE THREAD

**Issue by nfancy** [egeulgen/pathfindR#89]
Hi, 

Thank you for this great package. I was wondering if it is possible to input a filtered genelist by logFC? I can see from the vignette that the run_pathfindR unction will subset based on p-value but can I further filter based on logFC?

BW
Nurun

**Comment by egeulgen** [comment]
Hello,
pathfindR does not have an option to subset based on LFC, you may use the base function `subset()` instead.
Best,
-E
