### ISSUE TITLE
installation of package ‘pathfindR’ had non-zero exit status / Error: callr subprocess failed: Invalid parent_resolve callback

### ISSUE THREAD

**Issue by yotammarton** [egeulgen/pathfindR#93]
**Describe the bug**
Unable to install pathfindR

** R Session Information:**
R version 4.1.0 (2021-05-18)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 11.4

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] processx_3.5.2    compiler_4.1.0    R6_2.5.0          cli_3.0.1         tools_4.1.0       htmltools_0.5.1.1 rstudioapi_0.13  
 [8] crayon_1.4.1      knitr_1.33        callr_3.7.0       xfun_0.25         digest_0.6.27     ps_1.6.0          rlang_0.4.11     
[15] pak_0.1.2.1      

**Additional context**
Cannot get pathfindR to install properly, have tried the following code, attached is the returned errors:

`install.packages("pathfindR")`
Warning in install.packages :
  installation of package ‘pathfindR’ had non-zero exit status

`install.packages("pak") # if you have not installed "pak"
pak::pkg_install("pathfindR")`
Error: callr subprocess failed: Invalid parent_resolve callback

Thank you

**Comment by egeulgen** [comment]
Hey can you try installing via devtools:

```r
install.packages("devtools") # if you have not installed "devtools" 
devtools::install_github("egeulgen/pathfindR")
```

**Comment by egeulgen** [comment]
this seems to be an issue with the `download.file method`. 
Maybe try setting it to something else (the default should be "auto"):

```r
options(download.file.method = "libcurl")
```
If this does not work, please open up an issue on [devtools](https://github.com/r-lib/devtools) as this is an issue related to that package.
Best,
-E

**Comment by yotammarton** [comment]
Thanks, 
options(download.file.method = "curl") worked for me.
