### ISSUE TITLE
Error with term_gene_heatmap and UpSet_plot

### ISSUE THREAD

**Issue by cristanchoa** [egeulgen/pathfindR#94]
Hi, Thank you for such a great program. I was able to obtain enrichment pathway information (output_df) with my dataset (input_df). However, when I try to use term_gene_heatmap() and UpSet_plot() I get the following error: "Error in input_testing(genes_df) : p values must all be numeric." 

I have opened it multiple times and the p values are numeric (example below). This is also the same samples I ran to get the enrichment, so it was able to pick up the p values then. Please let me know if there is anything I am missing.

Thank you, 
Ana

input_df:
  GENE  CHANGE P_VALUE
  <chr>  <dbl>   <dbl>
1 P4ha1 -0.952   1e-13
2 Xpo1  -0.958   1e-13
3 Stmn4 -0.685   1e-13
4 Kdm3a -0.615   1e-13

RSession 
R version 4.0.5 (2021-03-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux 8.2 (Ootpa)

Matrix products: default
BLAS:   /cm/shared/apps_chop/R/4.0.5/lib64/R/lib/libRblas.so
LAPACK: /cm/shared/apps_chop/R/4.0.5/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] magrittr_2.0.1       pixmap_0.4-12        magick_2.7.2         future.callr_0.6.1  
 [5] future_1.21.0        callr_3.7.0          pak_0.1.2.1          pathfindR_1.6.1     
 [9] forcats_0.5.1        stringr_1.4.0        dplyr_1.0.7          purrr_0.3.4         
[13] readr_2.0.0          tidyr_1.1.3          tibble_3.1.3         ggplot2_3.3.5       
[17] tidyverse_1.3.1      msigdbr_7.4.1        readxl_1.3.1         pathfindR.data_1.1.1

loaded via a namespace (and not attached):
 [1] colorspace_2.0-2   ellipsis_0.3.2     class_7.3-18       modeltools_0.2-23 
 [5] mclust_5.4.7       fs_1.5.0           rstudioapi_0.13    listenv_0.8.0     
 [9] farver_2.1.0       graphlayouts_0.7.1 ggrepel_0.9.1      flexmix_2.3-17    
[13] bit64_4.0.5        fansi_0.5.0        lubridate_1.7.10   xml2_1.3.2        
[17] codetools_0.2-18   R.methodsS3_1.8.1  doParallel_1.0.16  robustbase_0.93-8 
[21] knitr_1.33         polyclip_1.10-0    jsonlite_1.7.2     rematch_1.0.1     
[25] broom_0.7.9        cluster_2.1.1      kernlab_0.9-29     dbplyr_2.1.1      
[29] R.oo_1.24.0        ggforce_0.3.3      compiler_4.0.5     httr_1.4.2        
[33] backports_1.2.1    assertthat_0.2.1   cli_3.0.1          tweenr_1.0.2      
[37] htmltools_0.5.1.1  tools_4.0.5        igraph_1.2.6       gtable_0.3.0      
[41] glue_1.4.2         tinytex_0.33       Rcpp_1.0.7         cellranger_1.1.0  
[45] vctrs_0.3.8        babelgene_21.4     iterators_1.0.13   fpc_2.2-9         
[49] ggraph_2.0.5       xfun_0.25          globals_0.14.0     ps_1.6.0          
[53] rvest_1.0.1        lifecycle_1.0.0    DEoptimR_1.0-9     MASS_7.3-53.1     
[57] scales_1.1.1       tidygraph_1.2.0    vroom_1.5.4        hms_1.1.0         
[61] parallel_4.0.5     gridExtra_2.3      stringi_1.7.3      foreach_1.5.1     
[65] rlang_0.4.11       pkgconfig_2.0.3    prabclus_2.3-2     evaluate_0.14     
[69] lattice_0.20-41    labeling_0.4.2     bit_4.0.4          tidyselect_1.1.1  
[73] processx_3.5.2     parallelly_1.27.0  R6_2.5.0           generics_0.1.0    
[77] DBI_1.1.1          pillar_1.6.2       haven_2.4.3        withr_2.4.2       
[81] nnet_7.3-15        modelr_0.1.8       crayon_1.4.1       utf8_1.2.2        
[85] tzdb_0.1.2         rmarkdown_2.10     viridis_0.6.1      grid_4.0.5        
[89] reprex_2.0.1       digest_0.6.27      diptest_0.76-0     R.utils_2.10.1    
[93] stats4_4.0.5       munsell_0.5.0      viridisLite_0.4.0 

I'm working on a PC, but through a Redhat based HPC.

**Comment by egeulgen** [comment]
hey @cristanchoa,

Do you mind sharing the data frame you use (`input_df `) as an RDS file so that I can check for any issues?

Best,
-E

**Comment by cristanchoa** [comment]
Hi,

Here it is!

Also, maybe germane to the problem, I can only get the initial enrichment analysis to work using what I think is the older version

input_processing(input = input, p_val_threshold = 0.05, pin_name_path  = "mmu_STRING", convert2alias = FALSE)

I get the same problem when I try to use run_pathfindR
Error in pathfindR::input_testing(input, p_val_threshold) :
  p values must all be numeric

Thanks in advance for your help!
Ana

From: Ege Ulgen ***@***.***>
Sent: Thursday, August 12, 2021 5:27 AM
To: egeulgen/pathfindR ***@***.***>
Cc: Cristancho, Ana G ***@***.***>; Mention ***@***.***>
Subject: [External]Re: [egeulgen/pathfindR] Error with term_gene_heatmap and UpSet_plot (#94)


hey @cristanchoa<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcristanchoa&data=04%7C01%7CCristanchoA%40chop.edu%7C49d6311cee754ac3399b08d95d7355f3%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637643572239810825%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=mwQzQbxt9z0jztvU58%2BYhqJu5KFFLK%2FjMbZAiH2t0vg%3D&reserved=0>,

Do you mind sharing the data frame you use (input_df ) as an RDS file so that I can check for any issues?

Best,
-E

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fegeulgen%2FpathfindR%2Fissues%2F94%23issuecomment-897486655&data=04%7C01%7CCristanchoA%40chop.edu%7C49d6311cee754ac3399b08d95d7355f3%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637643572239820819%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=K8qkO2oaskoWipSVMcYhtu1tCS04uoP4k85hloSpjyE%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FASPDMCEK7BRNYO5W3QORMH3T4OHWBANCNFSM5B7IBSXQ&data=04%7C01%7CCristanchoA%40chop.edu%7C49d6311cee754ac3399b08d95d7355f3%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637643572239820819%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=5xVa5%2FSfj1e8%2FC7Pq0I4v%2F%2FIpT%2F%2FptiNN%2FGfBzSno80%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CCristanchoA%40chop.edu%7C49d6311cee754ac3399b08d95d7355f3%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637643572239830813%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=CzqMmS7hb%2Bc58swXq1pEOr4RBgV4CNbzE2fQTpz3l1s%3D&reserved=0> or Android<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7CCristanchoA%40chop.edu%7C49d6311cee754ac3399b08d95d7355f3%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637643572239830813%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ln1adP%2BOqFj6Tr9k4ZTe1VO%2F4qAsn2MrvOvPR0B9pSQ%3D&reserved=0>.
** This email originated from an EXTERNAL sender to CHOP. Proceed with caution when replying, opening attachments, or clicking links. Do not disclose your CHOP credentials, employee information, or protected health information to a potential hacker**.

**Comment by egeulgen** [comment]
Hey @cristanchoa ,
The attachment isn’t there. I’m guessing your input is a tibble and that’s what causes the issue. Can you try running `as.data.frame()` first?

**Comment by cristanchoa** [comment]
Here goes again. I tested reloading it to my system. I think this should work. Thanks!

From: Ege Ulgen ***@***.***>
Sent: Friday, August 13, 2021 12:15 PM
To: egeulgen/pathfindR ***@***.***>
Cc: Cristancho, Ana G ***@***.***>; Mention ***@***.***>
Subject: [External]Re: [egeulgen/pathfindR] Error with term_gene_heatmap and UpSet_plot (#94)


Hey @cristanchoa<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcristanchoa&data=04%7C01%7CCristanchoA%40chop.edu%7C2bba2ee51bb54cc04fce08d95e758df8%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637644681268923087%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=dnG48xvTxAuTST6BF74ykxaM27MUHz7w4fo6jct74nk%3D&reserved=0> ,
The attachment isn't there. I'm guessing your input is a tibble and that's what causes the issue. Can you try running as.data.frame() first?

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fegeulgen%2FpathfindR%2Fissues%2F94%23issuecomment-898573229&data=04%7C01%7CCristanchoA%40chop.edu%7C2bba2ee51bb54cc04fce08d95e758df8%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637644681268933083%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qvLdI6MO2KlGAOC5vTkmngQcIlOWEQ3Qw4DpDzIoOiQ%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FASPDMCBELFQ7B2QM6XEZMV3T4VAJVANCNFSM5B7IBSXQ&data=04%7C01%7CCristanchoA%40chop.edu%7C2bba2ee51bb54cc04fce08d95e758df8%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637644681268933083%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=w4G5%2FgjCalRS9fuZ2MMd6ciI9bXUvPAGTKFLqNRk5w0%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CCristanchoA%40chop.edu%7C2bba2ee51bb54cc04fce08d95e758df8%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637644681268943078%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2BBSINlhrcwmFQwl3pm56nT5WkeCJOQu7iSxpTQp6T6U%3D&reserved=0> or Android<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7CCristanchoA%40chop.edu%7C2bba2ee51bb54cc04fce08d95e758df8%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637644681268943078%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=teQYcxU9eziFzrmhYxZ9%2F6B0bFwpJ0MxWJCmUj8RI%2Bc%3D&reserved=0>.
** This email originated from an EXTERNAL sender to CHOP. Proceed with caution when replying, opening attachments, or clicking links. Do not disclose your CHOP credentials, employee information, or protected health information to a potential hacker**.

**Comment by cristanchoa** [comment]
I see what you mean now. Yes, all the commands now work when I process use as.data.frame() on the initial file. Thank you!!
