### ISSUE TITLE
Unable to Read Font "helvetica"

### ISSUE THREAD

**Issue by evofish** [egeulgen/pathfindR#96]
Hello all this is my first time using pathfindR and I am having an issue running the example dataset "RA_input" as test. 

When I just run the command: 

> run_pathfindR(RA_input)

I get the following

_`n_processes` is set to `iterations` because `iterations` < `n_processes`
There is already a directory named "pathfindR_Results".
Writing the result to "pathfindR_Results(5)" not to overwrite any previous results.
## Testing input
The input looks OK
## Processing input. Converting gene symbols,
          if necessary (and if human gene symbols provided)
Number of genes provided in input: 572
Number of genes in input after p-value filtering: 572
Could not find any interactions for 5 (0.87%) genes in the PIN
Final number of genes in input: 567
## Annotating involved genes and visualizing enriched terms
Downloading pathway diagrams of 10 KEGG pathways

  |===========================================================================================| 100%
Saving colored pathway diagrams of 10 KEGG pathways

  |                                                                                           |   0%

Error in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)) : 
  rsession: UnableToReadFont `helvetica' @ error/annotate.c/RenderFreetype/1396_

--- 

It seems like the error is the lack of helvetica con my computer, which I have no idea how to solve. This is the first time I see this type of error for any sort of graph or analysis I have run with R. 

This is with R 4.1.1 and I had to "force" install some of the BioConductor dependencies to make it run. I also had a to install the latest version of Java available for mac (14) to make the pipeline work. 

Any suggestions would be greatly appreciated.

**Comment by evofish** [comment]
<img width="1186" alt="Screen Shot 2021-08-20 at 2 21 12 PM" src="https://user-images.githubusercontent.com/45925606/130283573-32d1c3e3-2bdc-40e3-a410-a5339d67c5ea.png">

**Comment by egeulgen** [comment]
hey @evofish,

You can find Helvetica [here](https://www.fonts.com/font/linotype/helvetica). While the font installation depends on your operating system, it's usually fairly easy (googling for it should help).

Hope this helps,
Best,
-E

**Comment by evofish** [comment]
Unfortunately it is much more complex than that. I have helvetica installed on my Mac by default, and it is on every user's library. When I run ggplot2 on itself I have no issue. 

The issue only comes up when I run pathfindr, giving me the error message: "Error in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)) :
rsession: UnableToReadFont `helvetica' @ error/annotate.c/RenderFreetype/1396_" 

If I try to run ggplot2 after running pathfindr I get the same error message from above. 

Is it possible that pathfindr is looking for fonts on a different folder? could this be triggered by one of the multiple dependencies? Any suggestion helps. Thanks again

**Comment by egeulgen** [comment]
hello again,
Some search revealed that this is an issue with magick (one of the dependencies). The solution provided [here](https://apple.stackexchange.com/questions/224285/why-does-image-magick-fail-to-read-fonts) suggests installing GhostScript via homebrew should resolve the issue:
```
brew install gs
```

Hope this resolves the issue,
Best,
-E

**Comment by evofish** [comment]
Thanks it is working properly now. I appreciate your support !
